[[language]]
name = "python"
auto-format = true

[[language]]
name = "markdown"
auto-format = true

[[language]]
name = "rst"
auto-format = true

[language-server.pylsp.config]
pylsp.configurationSources = "flake8"

pylsp.plugins.flake8.enabled = true
pylsp.plugins.black.enabled = true

pylsp.plugins.autopep8.enabled = false
pylsp.plugins.pycodestyle.enabled = false
pylsp.plugins.pyflakes.enabled = false
pylsp.plugins.pydocstyle.enabled = false
pylsp.plugins.pylint.enabled = false
