work_mins: 20 # work session length

work_msg: Focus on your task # work session message (shown in terminal and notification)

short_break_mins: 5 # short break session length

short_break_msg: Take a breather # short break session message (shown in terminal and notification)

long_break_mins: 15 # long break session length

long_break_msg: Take a long break # long break session message (shown in terminal and notification)

long_break_interval: 4 # number of sessions before long break

notify: true # show desktop notifications

auto_start_work: false # Automatically start the next work session

auto_start_break: true # Automatically start the next break session

24hr_clock: true # Show time in 24 hour format

sound: '' # name of ambient sound to play

sound_on_break: false # play ambient sound during break sessions

dark_theme: true # use colours befitting a dark background

session_cmd: '' # execute an arbitrary command after each session
