directory: ~/Sync/Music
library: ~/Sync/Music/beets-library.db
plugins: fetchart embedart fromfilename info edit

paths:
  default: $albumartist/$album%aunique{}/$track $title
  singleton: $artist/Non-Album/$title

fetchart:
  auto: true
  cautious: yes

embedart:
  auto: yes
  ifempty: yes
