directory: ~/Sync/Music
library: ~/Sync/Music/beets-library.db
plugins:
  - musicbrainz
  - fromfilename
  - info
  - edit
  - fetchart
  - embedart
  - lyrics

paths:
  default: $albumartist/$album%aunique{}/$track $title
  singleton: $artist/Non-Album/$title

import:
  copy: yes

fetchart:
  auto: true
  cautious: yes

embedart:
  auto: yes
  ifempty: yes

lyrics:
  auto: yes
  sources: "*"
